Fixed RSA key pair generation method
PointyCastle/pointycastle pull request #135
Opened 2018-07-23 19:33 UTC by proteye

Fixed RSA key pair generation method.

2018-07-31 11:04 UTC, shutup commented
i use this code in flutter,and it is run,thx!

2018-08-01 09:01 UTC, stevenroose requested changes

2018-08-01 09:01 UTC, stevenroose commented on lib/key_generators/rsa_key_generator.dart
> -        if (q.mod(e) == 1) {
Changing `mod` for `modInverse`, that seems not correct.. I think the `BigInt` method has the `%` operator implemented. So I think you can do `q % e == BigInt.one`.

2018-08-01 09:01 UTC, stevenroose commented on lib/key_generators/rsa_key_generator.dart
> -  AsymmetricKeyPair generateKeyPair() {
Why a generic method?

2018-10-04 15:34 UTC, stevenroose commented
This commit should have been included in https://github.com/PointyCastle/pointycastle/pull/148. Could you, @proteye or @yshrsmz confirm this? Then this can be closed.

Thanks nonetheless!

2018-10-04 15:38 UTC, yshrsmz commented
yes, I had included commits from this PR, as these were needed to make the tests passed

2018-10-04 15:53 UTC, stevenroose commented
K, then I'm closing this. Thanks again!

2018-10-04 15:53 UTC, closed without merging

2018-10-04 15:56 UTC, proteye commented
Ok. Thank you!