Add Blake2b
PointyCastle/pointycastle pull request #164
Opened 2019-01-11 04:34 UTC by bbedward

This is a rebase of #113.

I'm using this for a flutter crypto currency wallet I'm working on, as seen implemented in this package: https://github.com/bbedward/flutter_nano_core

2019-02-19 16:07 UTC, stevenroose commented
Hmm, it'd be nice if this PR could work on top of the commits from #113. Both to give credit to the original author and to have the name of the implementer on top of the commit in case someone has questions about it later.

2019-02-19 16:09 UTC, stevenroose commented
In that case, I could merge this next week and put it into a release as well.

2019-02-20 00:21 UTC, bbedward commented
I'll rebase it soon, originally it was just for personal usage but I'll redo it to preserve the original commits

2019-02-20 14:42 UTC, stevenroose commented
Thanks!

2019-02-20 14:50 UTC, bbedward commented
@stevenroose Re-based this pull request to include @jminer's commit

2019-02-20 15:10 UTC, stevenroose requested changes

2019-02-20 15:10 UTC, stevenroose commented on test/test/digest_tests.dart
> + f or(var i = 0; i < plainText.length; ++i) {
There is a type on this line.

2019-02-20 15:17 UTC, bbedward commented on test/test/digest_tests.dart
> + f or(var i = 0; i < plainText.length; ++i) {
Pushed fix,

also confirmed test passes

`00:00 +31: Blake2b: digest: (empty string)
00:00 +32: Blake2b: digest: Lorem ipsum dolor sit amet[...]
00:00 +33: Blake2b: digest: En un lugar de La Mancha, [...]
00:00 +34: Blake2b: digest: Lorem ipsum dolor sit amet[...]
00:00 +35: Blake2b: digest: Lorem ipsum dolor sit amet[...]`

2019-02-20 16:09 UTC, merged

2019-02-20 16:09 UTC, stevenroose commented
Thanks!